---
require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 2.3

Metrics/BlockLength:
  Exclude:
    - "Gemfile"
    - "spec/**/*"

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 120
